# coding: UTF-8

# noinspection PyPep8Naming
class lib:
    SYS_io_setup: int = ...
    SYS_io_destroy: int = ...
    SYS_io_getevents: int = ...
    SYS_io_submit: int = ...
    SYS_io_cancel: int = ...
